// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ8eh68yztGdSj5dLvY1Zjxt3NASShNb4',
    appId: '1:797385471626:web:7364d5e9ce3daf55829f73',
    messagingSenderId: '797385471626',
    projectId: 'bytebank-app-f79fb',
    authDomain: 'bytebank-app-f79fb.firebaseapp.com',
    storageBucket: 'bytebank-app-f79fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX5XQEgGfyXfNTtHx6iLjWVzotxx0n6ys',
    appId: '1:884410934565:android:d72ca8bf15fa5abde7a6cc',
    messagingSenderId: '884410934565',
    projectId: 'bytebank-app-90ef0',
    storageBucket: 'bytebank-app-90ef0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5AXgrqnV7VsxMIQv5OK_5QZSLvrr-ASk',
    appId: '1:884410934565:ios:a6216901ab13fdd5e7a6cc',
    messagingSenderId: '884410934565',
    projectId: 'bytebank-app-90ef0',
    storageBucket: 'bytebank-app-90ef0.firebasestorage.app',
    iosBundleId: 'com.example.bytebankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBNuCYE4aJQrXSg34c1lKdVbRz_kkO06M',
    appId: '1:797385471626:ios:da08d2b91b6076dd829f73',
    messagingSenderId: '797385471626',
    projectId: 'bytebank-app-f79fb',
    storageBucket: 'bytebank-app-f79fb.firebasestorage.app',
    iosBundleId: 'com.example.bytebankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ8eh68yztGdSj5dLvY1Zjxt3NASShNb4',
    appId: '1:797385471626:web:add53a3f4415feea829f73',
    messagingSenderId: '797385471626',
    projectId: 'bytebank-app-f79fb',
    authDomain: 'bytebank-app-f79fb.firebaseapp.com',
    storageBucket: 'bytebank-app-f79fb.firebasestorage.app',
  );
}